### PR TITLE
Use pool of buffers to reduce GC

### PR DESCRIPTION
**Pull request by CaptainCodeman**
Some reference articles:

http://www.akshaydeo.com/blog/2017/12/23/How-did-I-improve-latency-by-700-percent-using-syncPool/
https://blog.questionable.services/article/using-buffer-pools-with-go/
https://blog.cloudflare.com/recycling-memory-buffers-in-go/

### CODE REVIEW

**Comment by CaptainCodeman** [comment]
Thanks for the feedback. How's this?

Benchmark of original:
```
BenchmarkJSON-8    1000000    1821 ns/op    304 B/op    4 allocs/op
```
Bench of PR:
```
BenchmarkJSON-8    1000000    1592 ns/op     96 B/op    2 allocs/op
```
Comparison:
```

benchmark           old ns/op     new ns/op     delta
BenchmarkJSON-8     1821          1592          -12.58%

benchmark           old allocs    new allocs    delta
BenchmarkJSON-8     4             2             -50.00%

benchmark           old bytes     new bytes     delta
BenchmarkJSON-8     304           96            -68.42%
```

**Comment by VojtechVitek** [comment]
Interesting, so it does escape after all.
```
$ go test -gcflags '-m -l' -bench=. -benchtime 5s

./responder.go:102:25: &buf escapes to heap
./responder.go:102:25: &buf escapes to heap
./responder.go:101:6: moved to heap: buf
```

**Comment by VojtechVitek** [comment]
The performance gain from this PR is very little. For more real use case:

```go
func init() {
    words := make([]string, 200)
    for i, _ := range words {
        words[i] = "word"
    }

    floats := make([]float64, 200)
    for i, _ := range floats {
        floats[i] = 42.0
    }

    obj = Obj{
        ID:      123,
        Name:    "Some data",
        Words:   []string{"one", "two", "three", "four", "five"},
        Numbers: []float64{1.0, 2.0, 3.0, 4.0, 5.0},
        Words:   words,
        Numbers: floats,
    }
    str = `{"ID":123,"Name":"Some data","Words":["one","two","three","four","five"],"Numbers":[1,2,3,4,5]}
`
)
}
```

```
# original
BenchmarkJSON-4   	  200000	     30176 ns/op	    2592 B/op	       5 allocs/op
PASS
ok  	github.com/go-chi/render	6.377s

# sync.Pool
BenchmarkJSON-4   	  200000	     29945 ns/op	     176 B/op	       3 allocs/op
PASS
ok  	github.com/go-chi/render	6.443s
```

**Comment by VojtechVitek** [comment]
How about if we don't use the buffer at all?

We could marshal into `w` directly and `panic()` json `.Encode()` error (which is unlikely, since it happens on `v` being a channel/func/complex type only).

```
BenchmarkJSON-4   	  300000	     29069 ns/op	     176 B/op	       3 allocs/op
PASS
ok  	github.com/go-chi/render	9.041s
```

```go
func JSON(w http.ResponseWriter, r *http.Request, v interface{}) {
	enc := json.NewEncoder(w)
	enc.SetEscapeHTML(true)
	if err := enc.Encode(v); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		panic(err)
	}

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	if status, ok := r.Context().Value(StatusCtxKey).(int); ok {
		w.WriteHeader(status)
	}
}
```

**Comment by CaptainCodeman** [comment]
> The performance gain from this PR is very little. For more real use case

It's more about reducing allocations to save the _eventual_ GC work which the B/op in your example shows to be less (176 vs 2592). I don't know how to have a benchmark show this offhand - this was all based on the results from running it over time (similar to the articles linked to)

**Comment by CaptainCodeman** [comment]
Wouldn't we lose the ability to set the http status if it wasn't buffered?

**Comment by VojtechVitek** [comment]
> It's more about reducing allocations to save the eventual GC work which the B/op in your example shows to be less (176 vs 2592).

I understand. However, GC will collect unused `sync.Pool` items too. So unless you run a REST API application that calls `render.JSON()` in a loop and does nothing else, there won't be much of a performance improvement. The bottle neck is always somewhere else.

> Wouldn't we lose the ability to set the http status if it wasn't buffered?

Good question. Let me try

**Comment by VojtechVitek** [comment]
I tried rendering struct with `chan int` type using `render.JSON()` to cause the very unlikely error:

The handler panicked, as expected (people should use recoverer middleware anyway, ie. `go-chi/chi/middleware.Recoverer`).
The REST client got HTTP 500 with `handler returned wrong body: got Internal Server Error` body.

That's totally fine in my opinion. Same error code, but less details exposed to the REST customer.

```
$ go test
Panic: json: unsupported type: chan int
goroutine 20 [running]:
runtime/debug.Stack(0x28, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/go-chi/chi/middleware.Recoverer.func1.1(0xc4201bc100, 0x145e720, 0xc4201ca000)
	/Users/vojtechvitek/go/src/github.com/go-chi/chi/middleware/recoverer.go:28 +0x1b6
panic(0x1395540, 0xc42015e2d0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/go-chi/render.JSON(0x145e720, 0xc4201ca000, 0xc4201bc100, 0x13da7e0, 0xc42015a230)
	/Users/vojtechvitek/go/src/github.com/go-chi/render/responder.go:105 +0x1c7
github.com/go-chi/render.TestJSON.func1(0x145e720, 0xc4201ca000, 0xc4201bc100)
	/Users/vojtechvitek/go/src/github.com/go-chi/render/responder_test.go:17 +0x6f
net/http.HandlerFunc.ServeHTTP(0x142bcf8, 0x145e720, 0xc4201ca000, 0xc4201bc100)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc420138070, 0x145e720, 0xc4201ca000, 0xc4201bc100)
	/Users/vojtechvitek/go/src/github.com/go-chi/chi/mux.go:415 +0x26d
github.com/go-chi/chi.(*Mux).(github.com/go-chi/chi.routeHTTP)-fm(0x145e720, 0xc4201ca000, 0xc4201bc100)
	/Users/vojtechvitek/go/src/github.com/go-chi/chi/mux.go:351 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42001ee00, 0x145e720, 0xc4201ca000, 0xc4201bc100)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/go-chi/chi/middleware.Recoverer.func1(0x145e720, 0xc4201ca000, 0xc4201bc100)
	/Users/vojtechvitek/go/src/github.com/go-chi/chi/middleware/recoverer.go:35 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc4200f0480, 0x145e720, 0xc4201ca000, 0xc4201bc100)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420138070, 0x145e720, 0xc4201ca000, 0xc4201bc000)
	/Users/vojtechvitek/go/src/github.com/go-chi/chi/mux.go:80 +0x1d4
net/http.serverHandler.ServeHTTP(0xc420089790, 0x145e720, 0xc4201ca000, 0xc4201bc000)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201a0000, 0x145eb20, 0xc420168140)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
--- FAIL: TestJSON (0.00s)
	responder_test.go:33: handler returned wrong status code: got 500 want 200
	responder_test.go:37: handler returned wrong body: got Internal Server Error
		 want {"ID":123,"Name":"Some data","Words":["one","two","three","four","five"],"Numbers":[1,2,3,4,5]}
FAIL
exit status 1
FAIL	github.com/go-chi/render	0.019s
```

**Comment by VojtechVitek** [comment]
Let's write to `w` directly and `panic()` on unlikely error. Can you commit on top of your changes? Thanks

**Comment by CaptainCodeman** [comment]
Thanks for the feedback

**Comment by VojtechVitek** [comment]
> Let's write to w directly and panic() on unlikely error. Can you commit on top of your changes? Thanks

 @CaptainCodeman pls let me know if you want to finish the PR with the above changes.

Thanks for your contribution. It was nice perf lesson to me :)

**Comment by CaptainCodeman** [comment]
Will do, just trying an alternative approach with channels so the buffers survive GC. It may be a little too specific to my needs though (using with AppEngine where I can easily limit the # of concurrent requests) so need to play around with it first.

**Pull request closed without merging**
